drop table if exists users;

create table if not exists users
(
    user_id bigint generated by default as identity not null,
    name    varchar(200)                            not null,
    email   varchar(200) unique                     not null
);