drop table if exists endpoints;

create table if not exists endpoints
(
    endpoint_id bigint generated by default as identity not null,
    app         varchar(200)                            not null,
    uri         varchar(200)                            not null,
    ip          varchar(100)                            not null,
    timestamp   timestamp without time zone             not null
);